name: spanners
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.9.2
  image_picker: ^0.6.7+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #录音
  flutter_plugin_record: ^0.2.1
  web_socket_channel: ^1.0.13
  dio: ^3.0.9
  shared_preferences: ^0.5.3+1
  provider: 4.3.1
  rxdart: 0.24.1
  flutter_screenutil: 2.3.1
  azlistview: 0.1.2
  lpinyin: 1.0.7
  loading_indicator_view: ^1.1.0
  #日期选择
  flutter_picker: 1.1.0
  date_format: ^1.0.8
  #全局Key
  get_it: ^3.0.0+1
  #图片 压缩
  multi_image_picker: ^4.6.1
  flutter_image_compress: ^0.7.0
  #listview 滑动出按钮
  flutter_slidable: ^0.5.4
  bot_toast: 3.0.3
  cached_network_image: 2.3.0
  #Cookie  验证
  cookie_jar: 1.0.1
  dio_cookie_manager: 1.0.0
  #视频压缩
  video_compress: 2.1.0
  #折线图 扇形 饼形 用数据统计展示
  charts_flutter: ^0.9.0
  #进度条
  percent_indicator: ^2.1.1+1
  #剪裁图片
  image_crop: ^0.3.4
  #轮播图
  flutter_swiper: ^1.1.6
  #支付宝sdk
  tobias: ^1.7.1+1
  #微信支付
  fluwx: ^2.5.0+1
  #扫描条形码
  barcode_scan: ^1.0.0
  # 获取文件夹
  path_provider: ^1.6.24
  #getuiflut: ^0.2.5
  webview_flutter: ^1.0.7
  im_flutter_sdk:
    git:
      url: https://github.com/easemob/im_flutter_sdk.git
      ref: dev

  #高德地图
  amap_base: ^0.3.5
  #跳转到其他地图
  url_launcher: ^5.5.0
  #极光推送
  jpush_flutter: ^0.6.3



dev_dependencies:
  flutter_test:
    sdk: flutter
    #视频播放插件
  video_player: ^0.10.11+2

  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - Assets/
    #系统出错
    - Assets/catach/
    # 空数据 背景图
    - Assets/alartIcon/
    #Home 相关  image
    - Assets/Home/
    # 技术圈
    - Assets/Technology/
    #app bar 相关
    - Assets/appbar/
    #交验页面
    - Assets/delivery_check_page/
    #资料文件
    - Assets/data/
    #天气图片
    - Assets/weather/
    #预约
    - Assets/apointMent/
    #好友列表
    - Assets/friend/
    # 派工
    - Assets/atwork/

    # 结算
    - Assets/settlement/

    # 施工
    - Assets/working/
    # vip
    - Assets/vipImage/
    # 全车检查
    - Assets/check/
    #个人中心
    - Assets/wecenter/
    #绩效统计
    - Assets/performance/
    #绩效统计
    - Assets/members/
    #库存管理
    - Assets/inventory/
    #绩效统计
    - Assets/employee/
    #运营统计
    - Assets/operationStatistics/
    #物品存储
    - Assets/storage/
    #扳手共享
    - Assets/share_shop/
    #考勤统计
    - Assets/attendance/
    #销售任务
    - Assets/salesTask/
    #救援
    - Assets/help/
    #扳手商城
    - Assets/spanner_store/
    #商城订单
    - Assets/store_order/
    #共享订单
    - Assets/share_order/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
